/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharamcynb;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class DelMed extends javax.swing.JFrame {

    /**
     * Creates new form DelMed
     */
    public DelMed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        lblDelMedHeader = new javax.swing.JLabel();
        lblMedName = new javax.swing.JLabel();
        txtMedName = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnArrow = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDelMedHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblDelMedHeader.setText("Delete Medication");
        jPanel1.add(lblDelMedHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 440, -1));

        lblMedName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMedName.setText("Medication Name");
        jPanel1.add(lblMedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        txtMedName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtMedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 250, 30));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 90, 40));

        btnArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.jpeg"))); // NOI18N
        btnArrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArrowActionPerformed(evt);
            }
        });
        jPanel1.add(btnArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 40));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin_login_page.jpeg"))); // NOI18N
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArrowActionPerformed
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_btnArrowActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        String medicationName = txtMedName.getText();
        int adminId = AdminSession.getAdminId();
        
        try{
            Connection conn;
            Statement st;
            PreparedStatement ps;
            ResultSet rs;
            conn = connectdb.createconnection();
            st = conn.createStatement();
            
            // Check if the medication name exists in the medication table
            String checkMedQuery = "SELECT md_id FROM medication WHERE medName = ?";
            ps = conn.prepareStatement(checkMedQuery);
            ps.setString(1, medicationName);
            rs = ps.executeQuery();

            if (rs.next()) {
                int medId = rs.getInt("md_id");

                // Count the number of pharmacies associated with the medication
                String countPharmaciesQuery = "SELECT COUNT(*) AS pharmacyCount FROM pharmamed " +
                                              "WHERE med_id = ?";
                ps = conn.prepareStatement(countPharmaciesQuery);
                ps.setInt(1, medId);
                rs = ps.executeQuery();
                rs.next();
                int pharmacyCount = rs.getInt("pharmacyCount");

                if (pharmacyCount <= 1) {
                    // Medication is associated with only one pharmacy or none
                    // Proceed to delete from both medication and pharmamed tables
                    String deleteFromBothQuery = "DELETE FROM medication WHERE md_id = ?; " +
                                                 "DELETE FROM pharmamed WHERE med_id = ? AND ph_id IN (SELECT pharma_id FROM pharma WHERE admin_id = ?)";
                    ps = conn.prepareStatement(deleteFromBothQuery);
                    ps.setInt(1, medId);
                    ps.setInt(2, medId);
                    ps.setInt(3, adminId);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Medication deleted successfully.");
                } else {
                    // Medication is associated with multiple pharmacies
                    // Proceed to delete from the current pharmacy's pharmamed table
                    String deleteFromPharmamedQuery = "DELETE FROM pharmamed " +
                                                      "WHERE med_id = ? AND ph_id IN (SELECT pharma_id FROM pharma WHERE admin_id = ?)";
                    ps = conn.prepareStatement(deleteFromPharmamedQuery);
                    ps.setInt(1, medId);
                    ps.setInt(2, adminId);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Medication deleted successfully from the pharmacy.");
                }
            } else {
                // Medication doesn't exist, show error message
                JOptionPane.showMessageDialog(null, "The medication name does not exist.");
            }

    
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DelMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DelMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DelMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DelMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DelMed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArrow;
    private javax.swing.JButton btnDelete;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDelMedHeader;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblMedName;
    private javax.swing.JTextField txtMedName;
    // End of variables declaration//GEN-END:variables
}
