/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharamcynb;

import pharamcynb.AdminSession;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import pharamcynb.connectdb;

/**
 *
 * @author HP
 */
public class updateMed extends javax.swing.JFrame {

    /**
     * Creates new form updateMed
     */
    public updateMed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        lblUpdateMedHeader = new javax.swing.JLabel();
        lblMedName = new javax.swing.JLabel();
        txtMedName = new javax.swing.JTextField();
        lblQty = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnArrow = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUpdateMedHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblUpdateMedHeader.setText("Update Informations");
        jPanel1.add(lblUpdateMedHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        lblMedName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMedName.setText("Medication Name");
        jPanel1.add(lblMedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        txtMedName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtMedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 230, 30));

        lblQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblQty.setText("Quantity");
        jPanel1.add(lblQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, 40));

        txtQty.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 202, 230, 30));

        lblPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPrice.setText("Price");
        jPanel1.add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        txtPrice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 282, 230, 30));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));

        btnArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.jpeg"))); // NOI18N
        btnArrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArrowActionPerformed(evt);
            }
        });
        jPanel1.add(btnArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 40));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin_login_page.jpeg"))); // NOI18N
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int adminId = AdminSession.getAdminId();
        System.out.println(adminId);
        String medicationName = txtMedName.getText();
        int Quantity = Integer.parseInt(txtQty.getText());
        int price = Integer.parseInt(txtPrice.getText());
        
        try{
            
            Connection conn;
            Statement st;
            PreparedStatement ps;
            ResultSet rs;
            conn = connectdb.createconnection();
            st = conn.createStatement();
            
            rs = st.executeQuery("SELECT pharma_id FROM pharma WHERE admin_id ='" + adminId + "'");
            int pharmacyId = -1;
            if (rs.next()) {
            pharmacyId = rs.getInt("pharma_id");
            System.out.println(pharmacyId);
            }
            
            String updateQuery = "UPDATE pharmamed SET quantity= ? , price= ? WHERE med_id IN (SELECT md_id FROM medication WHERE medName= ? ) AND ph_id = ?";
            ps = conn.prepareStatement(updateQuery);
            ps.setInt(1, Quantity);
            ps.setInt(2, price);
            ps.setString(3, medicationName);
            ps.setInt(4, pharmacyId);
            ps.executeUpdate();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnArrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArrowActionPerformed
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_btnArrowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateMed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArrow;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblMedName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblUpdateMedHeader;
    private javax.swing.JTextField txtMedName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
}
