/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharamcynb;

import pharamcynb.AdminSession;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import pharamcynb.connectdb;

/**
 *
 * @author HP
 */
public class viewReservation extends javax.swing.JFrame {

    /**
     * Creates new form viewReservation
     */
    public viewReservation() {
        initComponents();
        int adminId = AdminSession.getAdminId();
        
        try{
        Connection conn;
        Statement st;
        ResultSet rs;
        conn = connectdb.createconnection();
        st = conn.createStatement();
        
        rs= st.executeQuery("SELECT phName,address From pharma WHERE admin_id='"+ adminId + "'");
        if(rs.next()){
            String pharmacyName = rs.getString("phName");
            lblPharmacyName.setText(pharmacyName);
            lblAdressHeader.setText(rs.getString("address"));
        }
        // Get the current local date and time
        LocalDateTime currentDateTime = LocalDateTime.now();

            // Format the date and time as a string
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String formattedDateTime = currentDateTime.format(formatter);

            // Set the formatted date and time as the text of the label
        dateLabel.setText(formattedDateTime);
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e, "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        lblResHeader = new javax.swing.JLabel();
        btnArrow = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblAllReservationHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOfReservation = new javax.swing.JTable();
        btnReservation = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblSearchReservation = new javax.swing.JLabel();
        lblClientEmail = new javax.swing.JLabel();
        txtSearchClient = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lblUserId = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        lblUserAdress = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        lblUserName1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPharmacyName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblDOB = new javax.swing.JLabel();
        txtUserAdress = new javax.swing.JTextField();
        lblQtyReserved = new javax.swing.JLabel();
        txtMedName = new javax.swing.JTextField();
        lblMedName1 = new javax.swing.JLabel();
        txtQtyReserved = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblDateOfReservation = new javax.swing.JLabel();
        txtDateOfReservation = new javax.swing.JTextField();
        lblAdressHeader = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnSell = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblMedicationName = new javax.swing.JLabel();
        txtMedNameSearched = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblResHeader.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblResHeader.setText("Reservations");

        btnArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.jpeg"))); // NOI18N
        btnArrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArrowActionPerformed(evt);
            }
        });

        lblAllReservationHeader.setFont(new java.awt.Font("Tahoma", 2, 28)); // NOI18N
        lblAllReservationHeader.setText("All Reservation");

        tableOfReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "name", "email", "address", "date of birth", "medication name", "Quantity reserved", "price", "date of reservation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableOfReservation.setRowHeight(24);
        tableOfReservation.setRowMargin(3);
        tableOfReservation.setShowHorizontalLines(false);
        tableOfReservation.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tableOfReservation);

        btnReservation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReservation.setText("view reservations");
        btnReservation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservationActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAllReservationHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(397, 397, 397))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(btnReservation)
                .addGap(109, 109, 109)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAllReservationHeader)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservation)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblSearchReservation.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        lblSearchReservation.setText("Search for a Reservation");

        lblClientEmail.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lblClientEmail.setText("client email");

        txtSearchClient.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblUserId.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblUserId.setText("Client Id");

        txtDOB.setBackground(new java.awt.Color(240, 240, 240));
        txtDOB.setBorder(null);

        lblUserAdress.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblUserAdress.setText("Client Adress");

        txtUserId.setBackground(new java.awt.Color(240, 240, 240));
        txtUserId.setBorder(null);

        lblUserName1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblUserName1.setText("Client name");

        txtUserName.setBackground(new java.awt.Color(240, 240, 240));
        txtUserName.setBorder(null);
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        lblPharmacyName.setFont(new java.awt.Font("Tahoma", 3, 22)); // NOI18N
        lblPharmacyName.setText("Pharmacy Name");

        lblDOB.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblDOB.setText("Date of birth");

        txtUserAdress.setBackground(new java.awt.Color(240, 240, 240));
        txtUserAdress.setBorder(null);

        lblQtyReserved.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblQtyReserved.setText("Quantity Reserved");

        txtMedName.setBackground(new java.awt.Color(240, 240, 240));
        txtMedName.setBorder(null);

        lblMedName1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblMedName1.setText("Medication name");

        txtQtyReserved.setBackground(new java.awt.Color(240, 240, 240));
        txtQtyReserved.setBorder(null);

        lblPrice.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblPrice.setText("Price");

        txtPrice.setBackground(new java.awt.Color(240, 240, 240));
        txtPrice.setBorder(null);

        lblDateOfReservation.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblDateOfReservation.setText("Date of reservation");

        txtDateOfReservation.setBackground(new java.awt.Color(240, 240, 240));
        txtDateOfReservation.setBorder(null);

        lblAdressHeader.setFont(new java.awt.Font("Tahoma", 3, 22)); // NOI18N
        lblAdressHeader.setText("Adress");

        dateLabel.setFont(new java.awt.Font("Tahoma", 3, 22)); // NOI18N
        dateLabel.setText("Date");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblDateOfReservation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDateOfReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblMedName1)
                        .addGap(11, 11, 11)
                        .addComponent(txtMedName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblQtyReserved)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQtyReserved, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblPharmacyName, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lblAdressHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblUserId)
                        .addGap(18, 18, 18)
                        .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUserName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUserAdress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUserAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDOB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblPharmacyName))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAdressHeader)
                            .addComponent(dateLabel))))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserId)
                    .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserName1)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserAdress)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDOB)
                    .addComponent(txtUserAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedName1)
                    .addComponent(lblQtyReserved)
                    .addComponent(txtQtyReserved, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfReservation)
                    .addComponent(txtDateOfReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnSell.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btnSell.setText("Sell");
        btnSell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblMedicationName.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblMedicationName.setText("Medication name");

        txtMedNameSearched.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(lblSearchReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(btnSell, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(btnDelete))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblClientEmail)
                                .addGap(31, 31, 31)
                                .addComponent(txtSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblMedicationName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMedNameSearched, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSearch)
                                .addGap(69, 69, 69)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSearchReservation)
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(lblMedicationName)
                    .addComponent(txtMedNameSearched, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSell)
                    .addComponent(btnDelete))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(677, 677, 677)
                        .addComponent(lblResHeader))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResHeader))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArrowActionPerformed
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_btnArrowActionPerformed

    private void btnReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservationActionPerformed
        int adminId = AdminSession.getAdminId();
        
        try{
            Connection conn;
            Statement st;
            PreparedStatement ps;
            ResultSet rs;
            conn = connectdb.createconnection();
            st = conn.createStatement();
            
            rs = st.executeQuery("SELECT pharma_id FROM pharma WHERE admin_id ='" + adminId + "'");
            int pharmacyId = -1;
            if (rs.next()) {
                pharmacyId = rs.getInt("pharma_id");
            }
            
            rs = st.executeQuery("SELECT Uname,email,user.address,DOB,medName,qtyReserved,total_price,Date_of_rsv FROM user\n" +
                                    "INNER JOIN reservation on user.userID=reservation.userID\n" +
                                    "INNER JOIN medication on reservation.med_ref_id=medication.md_id\n" +
                                    "INNER JOIN pharmamed on medication.md_id=pharmamed.med_id\n" +
                                    "INNER JOIN pharma on pharmamed.ph_id=pharma.pharma_id\n" +
                                    "WHERE p_id='"+ pharmacyId+ "'");
            
            DefaultTableModel model = (DefaultTableModel) tableOfReservation.getModel();
                model.setRowCount(0);
                if (!rs.isBeforeFirst()) { // Check if the result set is empty
                        JOptionPane.showMessageDialog(null, "No reservation found.");
                    } else {
                        while (rs.next()) {
                            model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8)});

                            }
                        }
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e, "Warning", JOptionPane.WARNING_MESSAGE);    
            }
    }//GEN-LAST:event_btnReservationActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableOfReservation.getModel();
                model.setRowCount(0);
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        String email = txtSearchClient.getText();
        int adminId = AdminSession.getAdminId();
        String userId = txtUserId.getText();
        String medName = txtMedNameSearched.getText();
        
        try{
            
            Connection conn;
            Statement st;
            ResultSet rs;
            conn = connectdb.createconnection();
            st = conn.createStatement();
            st.executeUpdate("UPDATE pharmamed \n" +
                                    "INNER JOIN medication ON pharmamed.med_id=medication.md_id\n" +
                                    "INNER JOIN reservation ON medication.md_id=reservation.med_ref_id\n" +
                                    "INNER JOIN user ON reservation.userID=user.userID\n" +
                                    "SET pharmamed.quantity=pharmamed.quantity - reservation.qtyReserved\n" +
                                    "WHERE user.email='"+ email + "' AND medication.medName='" + medName+ "'");
            
            rs = st.executeQuery("SELECT pharma_id FROM pharma WHERE admin_id ='" + adminId + "'");
            int pharmacyId = -1;
            if (rs.next()) {
                pharmacyId = rs.getInt("pharma_id");
            }
            
            rs = st.executeQuery("SELECT med_id From pharmamed INNER JOIN medication on pharmamed.med_id=medication.md_id WHERE ph_id='"+pharmacyId+"'"
                    + " AND medication.medName='"+medName+"'");
            int medicationId = -1;
            if(rs.next()){
                medicationId = rs.getInt("med_id");
            }
            
            rs = st.executeQuery("SELECT quantity FROM pharmamed WHERE med_id='"+medicationId+"' AND ph_id='"+pharmacyId+"'");
            int quantity = -1;
            if(rs.next()){
                quantity = rs.getInt("quantity");
            }
            if(quantity == 0){
                st.executeUpdate("DELETE FROM pharmamed WHERE quantity='0' AND ph_id='"+pharmacyId+"'");
            }
            
            st.executeUpdate("DELETE FROM reservation WHERE userID='"+ userId+ "' AND med_ref_id='"+medicationId+"'");
            
            
            printRecord(jPanel4);
            setVisible(false);
            new viewReservation().setVisible(true);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e, "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSellActionPerformed

    private void printRecord(JPanel jPanel4) {
        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setJobName("Print Record");
        pj.setPrintable((Graphics graphics, PageFormat pageFormat, int pageIndex) -> {
            if (pageIndex > 0) {
                return Printable.NO_SUCH_PAGE;
            }
            Graphics2D graphics2D = (Graphics2D) graphics;
            graphics2D.translate(pageFormat.getImageableX() * 2, pageFormat.getImageableY() * 2);
            graphics2D.scale(0.5, 0.5);
            jPanel4.paint(graphics2D);
            return Printable.PAGE_EXISTS;

        });
        boolean returningResult = pj.printDialog();
        if (returningResult) {
            try {
                pj.print();

            } catch (PrinterException printerException) {
                JOptionPane.showMessageDialog(this, "Print Error" + printerException.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }

    }
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try{
            
            String email = txtSearchClient.getText();
            String MedicationName = txtMedNameSearched.getText();
            
            txtUserId.setEditable(false);
            txtUserName.setEditable(false);
            txtUserAdress.setEditable(false);
            txtDOB.setEditable(false);
            txtMedName.setEditable(false);
            txtQtyReserved.setEditable(false);
            txtPrice.setEditable(false);
            txtDateOfReservation.setEditable(false);
            
            Connection conn;
            Statement st;
            ResultSet rs;
            conn = connectdb.createconnection();
            st = conn.createStatement();
            
            rs = st.executeQuery("SELECT user.userID,Uname,user.address,DOB,medName,qtyReserved,total_price,Date_of_rsv FROM user\n" +
                                    "INNER JOIN reservation on user.userID=reservation.userID\n" +
                                    "INNER JOIN medication on reservation.med_ref_id=medication.md_id\n" +
                                    "WHERE email='"+email+"' AND medication.medName='"+ MedicationName + "'");
            if(rs.next()){
                txtUserId.setText(rs.getString(1));
                txtUserName.setText(rs.getString(2));
                txtUserAdress.setText(rs.getString(3));
                txtDOB.setText(rs.getString(4));
                txtMedName.setText(rs.getString(5));
                txtQtyReserved.setText(rs.getString(6));
                txtPrice.setText(rs.getString(7));
                txtDateOfReservation.setText(rs.getString(8));
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e, "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String userId = txtUserId.getText();
        String medName = txtMedNameSearched.getText();
        int adminId = AdminSession.getAdminId();
        
        try{
            
            Connection conn;
            Statement st;
            ResultSet rs;
            conn = connectdb.createconnection();
            st = conn.createStatement();
            
            rs = st.executeQuery("SELECT pharma_id FROM pharma WHERE admin_id ='" + adminId + "'");
            int pharmacyId = -1;
            if (rs.next()) {
                pharmacyId = rs.getInt("pharma_id");
            }
            
            rs = st.executeQuery("SELECT med_id From pharmamed INNER JOIN medication on pharmamed.med_id=medication.md_id WHERE ph_id='"+pharmacyId+"'"
                    + " AND medication.medName='"+medName+"'");
            int medicationId = -1;
            if(rs.next()){
                medicationId = rs.getInt("med_id");
            }
            
            st.executeUpdate("DELETE FROM reservation WHERE userID='"+ userId+ "' AND med_ref_id='"+medicationId+"'");
            
            setVisible(false);
            new viewReservation().setVisible(true);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e, "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArrow;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReservation;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSell;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAdressHeader;
    private javax.swing.JLabel lblAllReservationHeader;
    private javax.swing.JLabel lblClientEmail;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDateOfReservation;
    private javax.swing.JLabel lblMedName1;
    private javax.swing.JLabel lblMedicationName;
    private javax.swing.JLabel lblPharmacyName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQtyReserved;
    private javax.swing.JLabel lblResHeader;
    private javax.swing.JLabel lblSearchReservation;
    private javax.swing.JLabel lblUserAdress;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JLabel lblUserName1;
    private javax.swing.JTable tableOfReservation;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDateOfReservation;
    private javax.swing.JTextField txtMedName;
    private javax.swing.JTextField txtMedNameSearched;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQtyReserved;
    private javax.swing.JTextField txtSearchClient;
    private javax.swing.JTextField txtUserAdress;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
